// ===== IELTS Vocabulary Bank (Part 1: 1–500) =====
window.WORD_BANK = [
  // ===== Level A1 =====
  ["hello","สวัสดี"],["goodbye","ลาก่อน"],["please","กรุณา"],["thank you","ขอบคุณ"],["sorry","ขอโทษ"],
  ["yes","ใช่"],["no","ไม่"],["book","หนังสือ"],["pen","ปากกา"],["student","นักเรียน"],
  ["teacher","ครู"],["school","โรงเรียน"],["food","อาหาร"],["water","น้ำ"],["home","บ้าน"],
  ["dog","สุนัข"],["cat","แมว"],["car","รถยนต์"],["bus","รถบัส"],["music","ดนตรี"],
  ["friend","เพื่อน"],["family","ครอบครัว"],["father","พ่อ"],["mother","แม่"],["brother","พี่ชาย/น้องชาย"],
  ["sister","พี่สาว/น้องสาว"],["baby","ทารก"],["boy","เด็กชาย"],["girl","เด็กหญิง"],["man","ผู้ชาย"],
  ["woman","ผู้หญิง"],["city","เมือง"],["village","หมู่บ้าน"],["house","บ้าน"],["room","ห้อง"],
  ["door","ประตู"],["window","หน้าต่าง"],["table","โต๊ะ"],["chair","เก้าอี้"],["bed","เตียง"],
  ["morning","เช้า"],["afternoon","บ่าย"],["evening","เย็น"],["night","กลางคืน"],["day","วัน"],
  ["week","สัปดาห์"],["month","เดือน"],["year","ปี"],["today","วันนี้"],["tomorrow","พรุ่งนี้"],
  ["yesterday","เมื่อวาน"],["sun","พระอาทิตย์"],["moon","พระจันทร์"],["star","ดาว"],["sky","ท้องฟ้า"],
  ["rain","ฝน"],["wind","ลม"],["snow","หิมะ"],["hot","ร้อน"],["cold","หนาว"],
  ["happy","มีความสุข"],["sad","เศร้า"],["angry","โกรธ"],["tired","เหนื่อย"],["hungry","หิว"],
  ["full","อิ่ม"],["beautiful","สวย"],["big","ใหญ่"],["small","เล็ก"],["long","ยาว"],
  ["short","สั้น"],["good","ดี"],["bad","แย่"],["easy","ง่าย"],["hard","ยาก"],
  ["open","เปิด"],["close","ปิด"],["go","ไป"],["come","มา"],["eat","กิน"],
  ["drink","ดื่ม"],["sleep","นอน"],["walk","เดิน"],["run","วิ่ง"],["read","อ่าน"],
  ["write","เขียน"],["speak","พูด"],["listen","ฟัง"],["look","มอง"],["see","เห็น"],
  ["buy","ซื้อ"],["sell","ขาย"],["sit","นั่ง"],["stand","ยืน"],["work","ทำงาน"],
  ["play","เล่น"],["study","เรียน"],["cook","ทำอาหาร"],["clean","ทำความสะอาด"],["wash","ล้าง"],
  ["drive","ขับรถ"],["ride","ขี่"],["swim","ว่ายน้ำ"],["sing","ร้องเพลง"],["dance","เต้น"],
  ["jump","กระโดด"],["draw","วาดภาพ"],["laugh","หัวเราะ"],["cry","ร้องไห้"],["think","คิด"],
  ["know","รู้"],["understand","เข้าใจ"],["remember","จำ"],["forget","ลืม"],["help","ช่วยเหลือ"],
  ["love","รัก"],["like","ชอบ"],["want","ต้องการ"],["need","จำเป็น"],["hope","หวัง"],
  ["wait","รอ"],["try","พยายาม"],["start","เริ่มต้น"],["finish","จบ"],["change","เปลี่ยน"],
  ["travel","เดินทาง"],["stay","พักอยู่"],["live","อาศัย"],["move","ย้าย"],["open","เปิด"],
  ["close","ปิด"],["turn on","เปิด (ไฟ, เครื่อง)"],["turn off","ปิด (ไฟ, เครื่อง)"],["begin","เริ่ม"],["end","สิ้นสุด"],
  ["answer","ตอบ"],["question","คำถาม"],["problem","ปัญหา"],["idea","ความคิด"],["thing","สิ่งของ"],
  ["place","สถานที่"],["person","บุคคล"],["animal","สัตว์"],["object","วัตถุ"],["time","เวลา"],
  ["money","เงิน"],["job","งาน"],["shop","ร้านค้า"],["market","ตลาด"],["hospital","โรงพยาบาล"],
  ["bank","ธนาคาร"],["school","โรงเรียน"],["university","มหาวิทยาลัย"],["restaurant","ร้านอาหาร"],["hotel","โรงแรม"],
  ["airport","สนามบิน"],["station","สถานี"],["street","ถนน"],["park","สวนสาธารณะ"],["shop","ร้านค้า"],
  ["doctor","หมอ"],["nurse","พยาบาล"],["police","ตำรวจ"],["firefighter","นักดับเพลิง"],["driver","คนขับรถ"],
  ["farmer","ชาวนา"],["teacher","ครู"],["student","นักเรียน"],["worker","คนงาน"],["chef","พ่อครัว/แม่ครัว"],
  ["engineer","วิศวกร"],["architect","สถาปนิก"],["artist","ศิลปิน"],["musician","นักดนตรี"],["actor","นักแสดง"],
  ["singer","นักร้อง"],["writer","นักเขียน"],["scientist","นักวิทยาศาสตร์"],["pilot","นักบิน"],["soldier","ทหาร"],
  ["lawyer","ทนาย"],["businessman","นักธุรกิจ"],["manager","ผู้จัดการ"],["cashier","แคชเชียร์"],["waiter","พนักงานเสิร์ฟ"],
  ["customer","ลูกค้า"],["shop assistant","พนักงานขาย"],["neighbor","เพื่อนบ้าน"],["tourist","นักท่องเที่ยว"],["visitor","ผู้มาเยือน"],

  // ===== Level A2 =====
  ["apple","แอปเปิ้ล"],["banana","กล้วย"],["orange","ส้ม"],["grape","องุ่น"],["mango","มะม่วง"],
  ["pineapple","สับปะรด"],["watermelon","แตงโม"],["strawberry","สตรอเบอร์รี่"],["lemon","มะนาว"],["cherry","เชอร์รี่"],
  ["rice","ข้าว"],["bread","ขนมปัง"],["milk","นม"],["tea","ชา"],["coffee","กาแฟ"],
  ["meat","เนื้อ"],["fish","ปลา"],["egg","ไข่"],["sugar","น้ำตาล"],["salt","เกลือ"],
  ["oil","น้ำมัน"],["butter","เนย"],["cheese","ชีส"],["cake","เค้ก"],["cookie","คุกกี้"],
  ["vegetable","ผัก"],["fruit","ผลไม้"],["soup","ซุป"],["juice","น้ำผลไม้"],["breakfast","อาหารเช้า"],
  ["lunch","อาหารกลางวัน"],["dinner","อาหารเย็น"],["kitchen","ห้องครัว"],["plate","จาน"],["spoon","ช้อน"],
  ["fork","ส้อม"],["knife","มีด"],["cup","ถ้วย"],["glass","แก้ว"],["bottle","ขวด"],
  ["shirt","เสื้อเชิ้ต"],["pants","กางเกง"],["shoes","รองเท้า"],["socks","ถุงเท้า"],["dress","ชุดเดรส"],
  ["hat","หมวก"],["jacket","เสื้อแจ็กเก็ต"],["bag","กระเป๋า"],["watch","นาฬิกา"],["phone","โทรศัพท์"],
  ["computer","คอมพิวเตอร์"],["television","โทรทัศน์"],["camera","กล้องถ่ายรูป"],["radio","วิทยุ"],["lamp","โคมไฟ"],
  ["mirror","กระจก"],["toothbrush","แปรงสีฟัน"],["soap","สบู่"],["towel","ผ้าเช็ดตัว"],["shampoo","แชมพู"],
  ["toilet","ห้องน้ำ"],["bathroom","ห้องอาบน้ำ"],["living room","ห้องนั่งเล่น"],["bedroom","ห้องนอน"],["kitchen","ห้องครัว"],
  ["floor","พื้น"],["wall","กำแพง"],["roof","หลังคา"],["garden","สวน"],["yard","ลานบ้าน"],
  ["tree","ต้นไม้"],["flower","ดอกไม้"],["grass","หญ้า"],["river","แม่น้ำ"],["mountain","ภูเขา"],
  ["sea","ทะเล"],["beach","ชายหาด"],["forest","ป่าไม้"],["lake","ทะเลสาบ"],["desert","ทะเลทราย"],
  ["animal","สัตว์"],["bird","นก"],["cow","วัว"],["pig","หมู"],["chicken","ไก่"],
  ["horse","ม้า"],["elephant","ช้าง"],["tiger","เสือ"],["lion","สิงโต"],["monkey","ลิง"],
  ["fish","ปลา"],["snake","งู"],["rabbit","กระต่าย"],["frog","กบ"],["bear","หมี"],
  ["zebra","ม้าลาย"],["giraffe","ยีราฟ"],["kangaroo","จิงโจ้"],["panda","แพนด้า"],["duck","เป็ด"],

  // ===== Level B1 =====
  ["health","สุขภาพ"],["education","การศึกษา"],["technology","เทคโนโลยี"],["internet","อินเทอร์เน็ต"],["environment","สิ่งแวดล้อม"],
  ["pollution","มลพิษ"],["recycling","การรีไซเคิล"],["climate","ภูมิอากาศ"],["global","ทั่วโลก"],["energy","พลังงาน"],
  ["electricity","ไฟฟ้า"],["medicine","ยา"],["disease","โรค"],["exercise","การออกกำลังกาย"],["diet","อาหารการกิน"],
  ["hospital","โรงพยาบาล"],["doctor","แพทย์"],["nurse","พยาบาล"],["patient","คนไข้"],["treatment","การรักษา"],
  ["learning","การเรียนรู้"],["language","ภาษา"],["communication","การสื่อสาร"],["culture","วัฒนธรรม"],["society","สังคม"],
  ["community","ชุมชน"],["tradition","ประเพณี"],["holiday","วันหยุด"],["festival","เทศกาล"],["travel","การเดินทาง"],
  ["tourism","การท่องเที่ยว"],["transport","การขนส่ง"],["train","รถไฟ"],["airport","สนามบิน"],["ticket","ตั๋ว"],
  ["map","แผนที่"],["journey","การเดินทาง"],["guide","ไกด์นำเที่ยว"],["passport","หนังสือเดินทาง"],["bag","กระเป๋า"],
  ["career","อาชีพ"],["business","ธุรกิจ"],["company","บริษัท"],["office","สำนักงาน"],["employee","พนักงาน"],
  ["boss","เจ้านาย"],["manager","ผู้จัดการ"],["meeting","การประชุม"],["customer","ลูกค้า"],["product","สินค้า"],
  ["service","บริการ"],["price","ราคา"],["market","ตลาด"],["shop","ร้านค้า"],["advertisement","โฆษณา"],
  ["money","เงิน"],["salary","เงินเดือน"],["bank","ธนาคาร"],["account","บัญชี"],["credit","เครดิต"],
  ["loan","เงินกู้"],["save","ออม"],["spend","ใช้จ่าย"],["buy","ซื้อ"],["sell","ขาย"],
  ["economy","เศรษฐกิจ"],["government","รัฐบาล"],["politics","การเมือง"],["law","กฎหมาย"],["justice","ความยุติธรรม"]
];
// ===== IELTS Vocabulary Bank (Part 2: 501–1000) =====
window.WORD_BANK.push(
  // ===== Level B2 =====
  ["innovation","นวัตกรรม"],["research","การวิจัย"],["experiment","การทดลอง"],["discovery","การค้นพบ"],["scientist","นักวิทยาศาสตร์"],
  ["laboratory","ห้องทดลอง"],["technology","เทคโนโลยี"],["development","การพัฒนา"],["improvement","การปรับปรุง"],["solution","ทางออก"],
  ["challenge","ความท้าทาย"],["success","ความสำเร็จ"],["failure","ความล้มเหลว"],["goal","เป้าหมาย"],["achievement","ความสำเร็จ"],
  ["plan","แผน"],["strategy","กลยุทธ์"],["method","วิธี"],["system","ระบบ"],["process","กระบวนการ"],
  ["production","การผลิต"],["industry","อุตสาหกรรม"],["factory","โรงงาน"],["material","วัสดุ"],["machine","เครื่องจักร"],
  ["energy","พลังงาน"],["electric","ไฟฟ้า"],["nuclear","นิวเคลียร์"],["solar","พลังงานแสงอาทิตย์"],["wind","ลม"],
  ["environment","สิ่งแวดล้อม"],["pollution","มลพิษ"],["recycle","รีไซเคิล"],["waste","ของเสีย"],["climate","ภูมิอากาศ"],
  ["temperature","อุณหภูมิ"],["oxygen","ออกซิเจน"],["carbon","คาร์บอน"],["planet","ดาวเคราะห์"],["earth","โลก"],
  ["universe","จักรวาล"],["galaxy","กาแล็กซี"],["astronomy","ดาราศาสตร์"],["gravity","แรงโน้มถ่วง"],["satellite","ดาวเทียม"],
  ["biology","ชีววิทยา"],["chemistry","เคมี"],["physics","ฟิสิกส์"],["mathematics","คณิตศาสตร์"],["engineering","วิศวกรรมศาสตร์"],
  ["computer","คอมพิวเตอร์"],["program","โปรแกรม"],["software","ซอฟต์แวร์"],["hardware","ฮาร์ดแวร์"],["network","เครือข่าย"],
  ["data","ข้อมูล"],["database","ฐานข้อมูล"],["digital","ดิจิทัล"],["robot","หุ่นยนต์"],["artificial intelligence","ปัญญาประดิษฐ์"],
  ["algorithm","อัลกอริทึม"],["website","เว็บไซต์"],["application","แอปพลิเคชัน"],["cloud","คลาวด์"],["security","ความปลอดภัย"],
  ["finance","การเงิน"],["banking","ธนาคาร"],["investment","การลงทุน"],["capital","เงินทุน"],["profit","กำไร"],
  ["loss","ขาดทุน"],["income","รายได้"],["expense","ค่าใช้จ่าย"],["budget","งบประมาณ"],["tax","ภาษี"],
  ["business","ธุรกิจ"],["entrepreneur","ผู้ประกอบการ"],["startup","ธุรกิจเริ่มต้น"],["marketing","การตลาด"],["advertising","โฆษณา"],
  ["promotion","โปรโมชั่น"],["brand","แบรนด์"],["customer","ลูกค้า"],["consumer","ผู้บริโภค"],["competition","การแข่งขัน"],
  ["sales","ยอดขาย"],["product","สินค้า"],["service","บริการ"],["quality","คุณภาพ"],["price","ราคา"],
  ["supply","อุปทาน"],["demand","อุปสงค์"],["market","ตลาด"],["trend","แนวโน้ม"],["growth","การเติบโต"],
  ["leadership","ความเป็นผู้นำ"],["management","การจัดการ"],["organization","องค์กร"],["company","บริษัท"],["corporation","บริษัทขนาดใหญ่"],
  ["employee","พนักงาน"],["employer","นายจ้าง"],["career","อาชีพ"],["experience","ประสบการณ์"],["skill","ทักษะ"],
  ["ability","ความสามารถ"],["training","การฝึกอบรม"],["responsibility","ความรับผิดชอบ"],["motivation","แรงจูงใจ"],["teamwork","การทำงานเป็นทีม"],
  ["interview","การสัมภาษณ์"],["resume","ประวัติย่อ"],["promotion","เลื่อนตำแหน่ง"],["salary","เงินเดือน"],["bonus","โบนัส"],
  ["communication","การสื่อสาร"],["discussion","การสนทนา"],["negotiation","การเจรจา"],["agreement","ข้อตกลง"],["contract","สัญญา"],
  ["decision","การตัดสินใจ"],["solution","คำตอบ"],["problem","ปัญหา"],["issue","ประเด็น"],["opinion","ความคิดเห็น"],
  ["perspective","มุมมอง"],["argument","การโต้แย้ง"],["reason","เหตุผล"],["example","ตัวอย่าง"],["evidence","หลักฐาน"],
  ["education","การศึกษา"],["knowledge","ความรู้"],["learning","การเรียนรู้"],["student","นักเรียน"],["teacher","ครู"],
  ["university","มหาวิทยาลัย"],["subject","วิชา"],["exam","การสอบ"],["grade","คะแนน"],["certificate","ประกาศนียบัตร"],
  ["library","ห้องสมุด"],["lecture","การบรรยาย"],["textbook","หนังสือเรียน"],["research","งานวิจัย"],["thesis","วิทยานิพนธ์"],
  ["training","การฝึกอบรม"],["project","โครงการ"],["presentation","การนำเสนอ"],["knowledge","ความรู้"],["creativity","ความคิดสร้างสรรค์"],

  // ===== Level C1 =====
  ["philosophy","ปรัชญา"],["psychology","จิตวิทยา"],["sociology","สังคมวิทยา"],["anthropology","มานุษยวิทยา"],["linguistics","ภาษาศาสตร์"],
  ["literature","วรรณกรรม"],["poetry","บทกวี"],["novel","นวนิยาย"],["drama","ละคร"],["history","ประวัติศาสตร์"],
  ["geography","ภูมิศาสตร์"],["politics","การเมือง"],["democracy","ประชาธิปไตย"],["economics","เศรษฐศาสตร์"],["philosopher","นักปรัชญา"],
  ["scientific","เชิงวิทยาศาสตร์"],["academic","เชิงวิชาการ"],["professional","มืออาชีพ"],["globalization","โลกาภิวัตน์"],["sustainability","ความยั่งยืน"],
  ["environmentalist","นักอนุรักษ์สิ่งแวดล้อม"],["biodiversity","ความหลากหลายทางชีวภาพ"],["renewable","หมุนเวียนได้"],["innovation","นวัตกรรม"],["entrepreneurship","ผู้ประกอบการ"],
  ["leadership","ภาวะผู้นำ"],["management","การบริหารจัดการ"],["collaboration","การร่วมมือ"],["creativity","ความคิดสร้างสรรค์"],["critical thinking","การคิดเชิงวิเคราะห์"],
  ["empathy","ความเห็นอกเห็นใจ"],["integrity","ความซื่อสัตย์"],["ethics","จริยธรรม"],["justice","ความยุติธรรม"],["freedom","เสรีภาพ"],
  ["equality","ความเท่าเทียม"],["diversity","ความหลากหลาย"],["innovation","นวัตกรรม"],["technology","เทคโนโลยี"],["artificial intelligence","ปัญญาประดิษฐ์"],
  ["machine learning","การเรียนรู้ของเครื่อง"],["robotics","หุ่นยนต์"],["cybersecurity","ความปลอดภัยไซเบอร์"],["blockchain","บล็อกเชน"],["virtual reality","ความจริงเสมือน"],
  ["metaverse","เมตาเวิร์ส"],["nanotechnology","นาโนเทคโนโลยี"],["biotechnology","เทคโนโลยีชีวภาพ"],["genetics","พันธุศาสตร์"],["cloning","การโคลนนิ่ง"],
  ["astronomy","ดาราศาสตร์"],["astrophysics","ฟิสิกส์ดาราศาสตร์"],["quantum","ควอนตัม"],["neuroscience","ประสาทวิทยา"],["psychotherapy","จิตบำบัด"],
  ["architecture","สถาปัตยกรรม"],["design","การออกแบบ"],["engineering","วิศวกรรม"],["aesthetics","สุนทรียศาสตร์"],["innovation","นวัตกรรม"],
  ["global warming","ภาวะโลกร้อน"],["climate change","การเปลี่ยนแปลงสภาพภูมิอากาศ"],["carbon footprint","รอยเท้าคาร์บอน"],["sustainable development","การพัฒนาที่ยั่งยืน"],["renewable energy","พลังงานหมุนเวียน"],
  ["digital economy","เศรษฐกิจดิจิทัล"],["cryptocurrency","สกุลเงินดิจิทัล"],["investment","การลงทุน"],["marketing strategy","กลยุทธ์การตลาด"],["financial planning","การวางแผนการเงิน"],
  ["entrepreneurial mindset","แนวคิดผู้ประกอบการ"],["global citizenship","พลเมืองโลก"],["intercultural communication","การสื่อสารระหว่างวัฒนธรรม"],["public speaking","การพูดในที่สาธารณะ"],["problem solving","การแก้ปัญหา"],
  ["time management","การจัดการเวลา"],["stress management","การจัดการความเครียด"],["decision making","การตัดสินใจ"],["emotional intelligence","ความฉลาดทางอารมณ์"],["self-awareness","การรู้จักตนเอง"],
  ["motivation","แรงจูงใจ"],["discipline","วินัย"],["goal setting","การตั้งเป้าหมาย"],["leadership skills","ทักษะความเป็นผู้นำ"],["team building","การสร้างทีม"],
  ["strategic planning","การวางแผนเชิงกลยุทธ์"],["risk management","การบริหารความเสี่ยง"],["corporate social responsibility","ความรับผิดชอบต่อสังคมขององค์กร"],["project management","การบริหารโครงการ"],["data analysis","การวิเคราะห์ข้อมูล"],
  ["innovation management","การจัดการนวัตกรรม"],["creative thinking","การคิดเชิงสร้างสรรค์"],["design thinking","การคิดเชิงออกแบบ"],["marketing campaign","แคมเปญการตลาด"],["customer experience","ประสบการณ์ลูกค้า"],
  ["branding","การสร้างแบรนด์"],["storytelling","การเล่าเรื่อง"],["content creation","การสร้างเนื้อหา"],["social media","สื่อสังคมออนไลน์"],["influencer","ผู้มีอิทธิพลบนสื่อ"],
  ["communication skills","ทักษะการสื่อสาร"],["negotiation skills","ทักษะการเจรจา"],["presentation skills","ทักษะการนำเสนอ"],["collaboration skills","ทักษะการร่วมมือ"],["conflict resolution","การแก้ไขความขัดแย้ง"],
  ["leadership development","การพัฒนาความเป็นผู้นำ"],["career development","การพัฒนาอาชีพ"],["lifelong learning","การเรียนรู้ตลอดชีวิต"],["personal growth","การเติบโตส่วนบุคคล"],["self-improvement","การพัฒนาตนเอง"],
  ["innovation culture","วัฒนธรรมนวัตกรรม"],["organizational behavior","พฤติกรรมองค์การ"],["human resources","ทรัพยากรมนุษย์"],["employee engagement","การมีส่วนร่วมของพนักงาน"],["performance evaluation","การประเมินผลการทำงาน"],
  ["talent management","การบริหารความสามารถบุคลากร"],["succession planning","การวางแผนสืบทอดตำแหน่ง"],["workplace diversity","ความหลากหลายในการทำงาน"],["corporate governance","ธรรมาภิบาลองค์กร"],["business ethics","จริยธรรมทางธุรกิจ"],
  ["innovation ecosystem","ระบบนิเวศนวัตกรรม"],["digital transformation","การเปลี่ยนผ่านดิจิทัล"],["customer satisfaction","ความพึงพอใจของลูกค้า"],["market research","การวิจัยตลาด"],["brand awareness","การรับรู้แบรนด์"],
  ["public relations","ประชาสัมพันธ์"],["media production","การผลิตสื่อ"],["film industry","อุตสาหกรรมภาพยนตร์"],["music industry","อุตสาหกรรมดนตรี"],["gaming industry","อุตสาหกรรมเกม"],
  ["performing arts","ศิลปะการแสดง"],["fine arts","ศิลปกรรม"],["visual arts","ทัศนศิลป์"],["photography","การถ่ายภาพ"],["cinematography","การถ่ายทำภาพยนตร์"],
  ["cultural heritage","มรดกทางวัฒนธรรม"],["moral values","คุณค่าทางศีลธรรม"],["spiritual development","การพัฒนาทางจิตวิญญาณ"],["mindfulness","สติ"],["gratitude","ความกตัญญู"]
);
